site_name: MAIT 2022 OOP - AI and NN
# Repository
repo_name: OOP_22_AI_NN
repo: https://github.com/jan-of-us/OOP_22_AI_NN
version: main
# Copyright
copyright: Jan Schiefer

nav:
    - Home: index.md
    - AI-Classification: 
        - Classification Overview: AI_Classification.md
        - Classification.py: AI_Classification/Classification.md
        - Classification_Data.py: AI_Classification/Classification_Data.md
        - NN_Classification.py: AI_Classification/NN_Classification.md
        - RF_Classification.py: AI_Classification/RF_Classification.md
    - AI-Regression: 
        - Regression Overview: AI_Regression.md
        - Regression.py: AI_Regression/Regression.md
        - Regression_Data.py: AI_Regression/Regression_Data.md
        - NN_Regression.py: AI_Regression/NN_Regression.md
        - RF_Regression.py: AI_Regression/RF_Regression.md
theme: readthedocs
